global:
  resolve_timeout: 5m

templates:
  - "/etc/alertmanager/template/*.tmpl"

route:
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 5m
  receiver: aws-sns
  routes:
    - matchers:
        - severity =~ "warning|critical"
      receiver: aws-sns
# Send alter via emails using AWS SNS
receivers:
  - name: aws-sns
    sns_configs:
      - sigv4:
          role_arn: <YOUR-ECS-INSTANCE-ROLE-ARN>
          region: us-east-1
        topic_arn: <YOUR-SNS-TOPIC-ARN>
        message: |
          text: |-
            {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
              *Description:* {{ .Annotations.description }}
              *Details:*
                {{ range .Labels.SortedPairs }} . *{{ .Name }}:* `{{ .Value }}`
                {{ end }}
            {{ end }}
